#!/bin/bash

set -e

tag=$(cat .version)

if [ -z "$tag" ]; then
    echo "No version found"
    exit 1
fi

echo "Waiting for GitHub workflow to start..."
sleep 5

WID=$(gh run list -b $tag --json databaseId --jq '.[0].databaseId')
[ -z "$WID" ] && echo "Workflow ID for $tag not found" && exit 1

gh run watch $WID
