#!/bin/bash

# access secret from secretsmanager
secrets=$(gcloud secrets versions access latest --secret="runner-secret")

# set secrets as env vars
# shellcheck disable=SC2206
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]')"
    export "${var?}"
done <<< "$secrets"

#stop and uninstall the runner service
cd /runner || exit
./svc.sh stop
./svc.sh uninstall

#remove the runner configuration
RUNNER_ALLOW_RUNASROOT=1  /runner/config.sh remove --unattended --token "$(curl -sS --request POST --url "https://api.github.com/repos/${repo}/actions/runners/remove-token" --header "authorization: Bearer ${token}" --header "content-type: application/json" | jq -r .token)"