#!/bin/bash

# This script removes all runners from the repo.
# Quick way to clean up after the demo.

set -euo pipefail

# variables
repo="mchmarny/grunner"

list=$(gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/${repo}/actions/runners" \
        --jq ".runners[].id")

if [ -z "$list" ]; then
  echo "No runners found"
  exit 0
fi

# For each workflow, cancel it
for id in $list; do
  echo "Cancelling workflow $id..."
  gh api \
  --method DELETE \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "/repos/${repo}/actions/runners/${id}"
done
