#!/bin/bash

# install
sudo apt-get update
sudo apt-get -y install jq

# access secret from secretsmanager
secrets=$(gcloud secrets versions access latest --secret="grunner")

# set secrets as env vars
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]' | tr -d '"')"
    export "${var?}"
done <<< "$secrets"

# Create folders
mkdir workspace
mkdir runner && cd runner

# github runner version
GH_RUNNER_VERSION="2.305.0"

# Download the latest runner package
curl -o runner.tar.gz \
     -L https://github.com/actions/runner/releases/download/v${GH_RUNNER_VERSION}/actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

# Extract installer
tar xzf ./runner.tar.gz
rm -f ./runner.tar.gz

# Dependencies
sudo bin/installdependencies.sh

# Get config variables 
ACTIONS_RUNNER_INPUT_NAME=$HOSTNAME
ACTIONS_RUNNER_INPUT_TOKEN="$(curl -sS \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${token}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${repo}/actions/runners/registration-token" | jq -r .token)"

# Configure runner
RUNNER_ALLOW_RUNASROOT=1 ./config.sh \
  --unattended \
  --replace \
  --work "../workspace" \
  --url "https://github.com/${repo}" \
  --token "$ACTIONS_RUNNER_INPUT_TOKEN" \
  --labels grunner

# Install and start runner service
sudo ./svc.sh install
sudo ./svc.sh start
