#!/bin/bash

# install
apt-get update
apt-get -y install jq

# access secret from secretsmanager
secrets=$(gcloud secrets versions access latest --secret="grunner")

# set secrets as env vars
# shellcheck disable=SC2206
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]')"
    export "${var?}"
done <<< "$secrets"

# Create a folder
mkdir actions-runner && cd actions-runner

# github runner version
GH_RUNNER_VERSION="2.305.0"

# Download the latest runner package
curl -o actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz \
     -L https://github.com/actions/runner/releases/download/v${GH_RUNNER_VERSION}/actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

# Extract installer
$ tar xzf ./actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

# Get token
ACTIONS_RUNNER_INPUT_TOKEN="$(curl -sS --request POST --url "https://api.github.com/repos/${repo}/actions/runners/registration-token" --header "authorization: Bearer ${token}"  --header 'content-type: application/json' | jq -r .token)"

# Configure runner
RUNNER_ALLOW_RUNASROOT=1 ./config.sh --unattended --url "https://github.com/${repo}" --token "$ACTIONS_RUNNER_INPUT_TOKEN"

# Run it
$ ./run.sh
