#!/bin/bash

gcloud compute instances create grunner-test \
    --project $PROJECT_ID \
    --zone us-west1-c \
    --machine-type e2-medium \
    --service-account "grunner-sa@$PROJECT_ID.iam.gserviceaccount.com" \
    --scopes https://www.googleapis.com/auth/cloud-platform \
    --image ubuntu-2204-jammy-v20230616 \
    --image-project ubuntu-os-cloud \
    --labels "environment=test,stack=github,component=runner"

# SSH into the Vm
# gcloud compute ssh grunner-test --zone us-west1-c --project $PROJECT_ID

# Delete the VM
# gcloud compute instances delete grunner-test --project $PROJECT_ID --zone us-west1-c
