#!/bin/bash

# Load Secrets from Secret Manager
secrets=$(gcloud secrets versions access latest --secret="grunner")
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]' | tr -d '"')"
    export "${var?}"
done <<< "$secrets"

# Get config variables 
ACTIONS_RUNNER_INPUT_NAME=$HOSTNAME
ACTIONS_RUNNER_INPUT_TOKEN="$(curl -sS \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${token}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${repo}/actions/runners/registration-token" | jq -r .token)"

# Stop and uninstall the runner service
cd /runner || exit
./svc.sh stop
./svc.sh uninstall

# Remove the runner configuration
RUNNER_ALLOW_RUNASROOT=1 ./config.sh remove \
  --token "$ACTIONS_RUNNER_INPUT_TOKEN"
