#!/bin/bash

# access secret from secretsmanager
secrets=$(gcloud secrets versions access latest --secret="grunner")

# set secrets as env vars
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]' | tr -d '"')"
    export "${var?}"
done <<< "$secrets"

# Create folders
mkdir workspace

# Get config variables 
ACTIONS_RUNNER_INPUT_NAME=$HOSTNAME
ACTIONS_RUNNER_INPUT_TOKEN="$(curl -sS \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${token}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${repo}/actions/runners/registration-token" | jq -r .token)"

# Pre and Post job scripts
# ACTIONS_RUNNER_HOOK_JOB_STARTED="/runner/job-started.sh"
ACTIONS_RUNNER_HOOK_JOB_COMPLETED="/runner/job-completed.sh"

# Configure runner
cd runner || exit
RUNNER_ALLOW_RUNASROOT=1 ./config.sh \
  --unattended \
  --replace \
  --work "../workspace" \
  --url "https://github.com/${repo}" \
  --token "$ACTIONS_RUNNER_INPUT_TOKEN" \
  --labels grunner

# Install and start runner service
./svc.sh install
./svc.sh start
