#!/bin/bash

# Extract data from the Google metadata service
getmd() {
  curl -sSfL "http://metadata.google.internal/computeMetadata/v1/${1}" \
    --header "Metadata-Flavor: Google"
}

# Capture configuration and credentials from instance metadata
GOOGLE_CLOUD_PROJECT="$(getmd "project/project-id")"
INSTANCE_ID="$(getmd "instance/id")"
INSTANCE_ZONE="$(getmd "instance/zone")"

# Load Secrets from Secret Manager
secrets=$(gcloud secrets versions access latest --secret="grunner")
while IFS= read -r line; do
    var="$(echo -e "${line}" | tr -d '[:space:]' | tr -d '"')"
    export "${var?}"
done <<< "$secrets"

# Create workspace folders
mkdir workspace

# Get config variables 
ACTIONS_RUNNER_INPUT_NAME=$HOSTNAME
ACTIONS_RUNNER_INPUT_TOKEN="$(curl -sS \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${token}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${repo}/actions/runners/registration-token" | jq -r .token)"

# Wire pre/post job scripts
ACTIONS_RUNNER_HOOK_JOB_STARTED="/runner/job-started.sh"
ACTIONS_RUNNER_HOOK_JOB_COMPLETED="/runner/job-completed.sh"

# Configure runner
cd runner || exit
RUNNER_ALLOW_RUNASROOT=1 ./config.sh \
  --unattended \
  --ephemeral \
  --work "/workspace" \
  --url "https://github.com/${repo}" \
  --token "$ACTIONS_RUNNER_INPUT_TOKEN" \
  --labels grunner

# Install and start runner service
./svc.sh install
./svc.sh start

# Add ops agent
curl -sSo agent.sh https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
chmod +x agent.sh
./agent.sh --also-install